name: tmna-data-core
channels:
  - conda-forge
dependencies:
  - google-cloud-aiplatform
  - db-dtypes
  - matplotlib
  - pybase64
  - pandas
  - langchain[all]
  - retry
  - numpy
  - streamlit
